services:
  - type: web
    name: ml-flask-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    autoDeploy: false  # we'll trigger deploys via Github Actions